Repository EdwardHaoranLee/WoodokuLearn, pull requests merged in 2022-08, with the labels that each got.

#67 fix(game): fail game when any shape cannot fit
  woodoku/game.py
  woodoku/tests/test_game.py
Labels: bug

#63 feat(art): ui art babe!
  Pipfile
  Pipfile.lock
  mypy.ini
  woodoku/entity/score_agent.py
  woodoku/entity/woodoku_board.py
  woodoku/entity/woodoku_shape.py
  woodoku/game.py
  woodoku/tests/entity/test_woodoku_board.py
  woodoku/ui/command_line_ui.py
  woodoku/ui/ui_interface.py
Labels: enhancement, visuals

#64 config(workflow): trying out codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: config

#61 test(ScoreAgent): test done for the scores hehe
  .pre-commit-config.yaml
  woodoku/tests/entity/test_score_agent.py
Labels: test

#60 Game Release
  .github/pull_request_template.md
  .github/workflows/black.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pylint.yaml
  .github/workflows/test.yaml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  Pipfile
  Pipfile.lock
  README.md
  mypy.ini
  setup.cfg
  setup.py
  woodoku/config.yaml
  woodoku/entity/score_agent.py
  woodoku/entity/woodoku_board.py
  woodoku/entity/woodoku_shape.py
  woodoku/exceptions/shape_out_of_board_error.py
  woodoku/game.py
  woodoku/tests/entity/test_score_agent.py
  woodoku/tests/entity/test_woodoku_board.py
  woodoku/tests/entity/test_woodoku_shape.py
  woodoku/tests/test_game.py
  woodoku/ui/command_line_ui.py
  woodoku/ui/ui_interface.py
  woodoku/ui/utils.py
Labels: release

#68 setup(learn): inital Reinforce Learning skeleton
  Pipfile
  Pipfile.lock
  learn/src/__init__.py
  learn/src/data/experiences.py
  learn/src/models/model.py
  learn/src/models/predict_model.py
  learn/src/models/train_model.py
  learn/src/visualization/visualize.py
  setup.py
Labels: design
