Repository EdwardHaoranLee/WoodokuLearn, pull requests merged in 2022-07, with the labels that each got.

#29 docs(PR): create pull request template
  .github/pull_request_template.md
Labels: documentation

#31 modify package and file names
  Woodoku/src/entity/score_agent.py
  Woodoku/src/entity/woodoku_board.py
  Woodoku/src/entity/woodoku_shape.py
  Woodoku/src/exceptions/exceptions.py
  Woodoku/src/game.py
  Woodoku/src/ui/command_line_ui.py
  Woodoku/src/ui/ui_interface.py
  Woodoku/tests/entity/test_score_agent.py
  Woodoku/tests/entity/test_woodoku_board.py
  Woodoku/tests/entity/test_woodoku_shape.py
Labels: refactor

#25 Fix several minor problems.
  Woodoku/src/entity/woodoku_board.py
  Woodoku/src/entity/woodoku_shape.py
Labels: bug

#40 28 setup python linter locally and in GitHub action
  .github/workflows/black.yaml
  .github/workflows/pylint.yaml
  .pre-commit-config.yaml
  .pylintrc
  Woodoku/src/entity/woodoku_board.py
  Woodoku/src/entity/woodoku_shape.py
  Woodoku/src/exceptions/shape_out_of_board_error.py
  Woodoku/src/game.py
  Woodoku/src/ui/command_line_ui.py
  Woodoku/src/ui/ui_interface.py
  Woodoku/tests/entity/test_woodoku_board.py
  setup.sh
Labels: config

#32 test woodokuboard
  Woodoku/tests/entity/test_woodoku_board.py
Labels: test

#48 refactor(woodoku): introduce woodoku local package
  Pipfile
  setup.cfg
  setup.py
  woodoku/config.yaml
  woodoku/entity/score_agent.py
  woodoku/entity/woodoku_board.py
  woodoku/entity/woodoku_shape.py
  woodoku/exceptions/shape_out_of_board_error.py
  woodoku/game.py
  woodoku/tests/entity/test_score_agent.py
  woodoku/tests/entity/test_woodoku_board.py
  woodoku/tests/entity/test_woodoku_shape.py
  woodoku/ui/command_line_ui.py
  woodoku/ui/ui_interface.py
Labels: refactor

#47 docs | config(README | Pipfile): development instruction and package dependency update
  Pipfile
  README.md
  setup.sh
Labels: documentation, config

#49 config(project): Add pytest to github action
  .github/workflows/pytest.yaml
  .gitignore
  Pipfile
  Pipfile.lock
  woodoku/tests/entity/test_woodoku_board.py
Labels: config

#51 config(mypy): setup mypy and refactor accordingly
  .github/workflows/pytest.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  mypy.ini
  woodoku/entity/score_agent.py
  woodoku/entity/woodoku_board.py
  woodoku/entity/woodoku_shape.py
  woodoku/game.py
  woodoku/tests/entity/test_woodoku_board.py
  woodoku/tests/entity/test_woodoku_shape.py
  woodoku/ui/ui_interface.py
Labels: refactor, config

#50 14 implement game logic test ie test game function in gamepy
  .gitignore
  woodoku/game.py
  woodoku/tests/test_game.py
Labels: test

#53 fix(ui): fix ui shape selection bug
  woodoku/ui/command_line_ui.py
Labels: bug

#57 fix(woodokuBoard): Should handle exception
  woodoku/entity/woodoku_board.py
  woodoku/tests/entity/test_woodoku_board.py
Labels: bug

#55 fix(commandlineUI): should only choose available
  woodoku/ui/command_line_ui.py
Labels: bug

#58 add x and y coordiate
  woodoku/entity/woodoku_board.py
Labels: enhancement
